### PR TITLE
Add config for shl-ips

### PR DESCRIPTION
**Pull request by ivan-c**
- Add initial public OIDC client for shl-ips creator/viewer (clientid `shl_creator`)
- Add service config for shl-creator and shl-server

### CODE REVIEW

**Review by daniellrgn — APPROVED** [review]
Looks good, though I'll have to take your word on most of this! To clarify, will the clientId here be what I'll need to sub into the SOF auth request on the shl client side?

**Comment by ivan-c** [comment]
>will the clientId here be what I'll need to sub into the SOF auth request on the shl client side?

Yup! 
Sorry I didn't add the relevant details for the shl-client service yet, but I realized there isn't a docker image I could pull. I added a couple PRs but wasn't sure which repo was the [right](https://github.com/uwcirg/shl-ips/pull/9) [one](https://github.com/uwcirg/shl-viewer/pull/1).

I'll add some config to pass it via environment variable but I'd start with just a hardcoded value for now

**Comment by ivan-c** [comment]
>will the clientId here be what I'll need to sub into the SOF auth request on the shl client side?

@daniellrgn 

Yup! 
Sorry I didn't add the relevant details for the shl-client service yet, but I realized there isn't a docker image I could pull. I added a couple PRs but wasn't sure which repo was the [right](https://github.com/uwcirg/shl-ips/pull/9) [one](https://github.com/uwcirg/shl-viewer/pull/1).

I'll add some config to pass it via environment variable but I'd start with just a hardcoded value for now

**Comment by ivan-c** [comment]
@daniellrgn

I added the docker-compose configs for the shl-creator, and server. However, it looks like the smart.health.links (API) server  still needs a central docker image. will work on that next

**Comment by ivan-c** [comment]
>it looks like the smart.health.links (API) server still needs a central docker image

done! see uwcirg/smart.health.links/pull/2

**Pull request merged**
