### PR TITLE
fix #187711406

### PR DESCRIPTION
**Pull request by victorlima02**
Increasing Maintainability:
- Refactored code to enhance readability and maintainability.
- Simplified complex logic structures for easier understanding and maintenance.

Replacing Deprecated Calls:
- Replaced deprecated API calls with their updated counterparts.
- Ensured compatibility with the latest versions of dependencies.

Enhanced Security Adjustments:
- Implemented improved security measures, particularly focusing on Cross-Site Scripting (XSS) vulnerabilities (see `kcSanitize()`)
- Conducted a thorough security review and updated vulnerable sections of the code.

Alignment with Keycloak Project:
- Updated themes to align more closely with the Keycloak project we previously prepared.
- Made the theme compatible with Keycloak versions 22, 23, and 24, ensuring readiness for future updates and removed code from version 19.

Removal of Redundant Code:
- Eliminated redundant code that varied between versions and required frequent maintenance.
- Streamlined the codebase to reduce the need for reevaluation with each upstream server change.

### CODE REVIEW

**Comment by mcjustin** [comment]
I added @ivan-c  as a reviewer here. This is not urgent, and I'm planning a release for prod today, so please don't merge this yet.

**Comment by ivan-c** [comment]
@victorlima02 could you add a description to this PR? 

I look [at the relevant PT story](https://www.pivotaltracker.com/n/projects/2671465/stories/187711406) and I thought it was fixed with 53064f2?

**Review by ivan-c — COMMENTED** [review]
@victorlima02 could you add a description to this PR? 

I look [at the relevant PT story](https://www.pivotaltracker.com/n/projects/2671465/stories/187711406) and I thought it was fixed with 53064f2?

**Comment by victorlima02** [comment]
This pull request includes significant updates aimed at improving the overall quality and security of our codebase. The main changes are as follows:

Increasing Maintainability:

Refactored code to enhance readability and maintainability.
Simplified complex logic structures for easier understanding and maintenance.

Replacing Deprecated Calls:
Replaced deprecated API calls with their updated counterparts.
Ensured compatibility with the latest versions of dependencies.

Enhanced Security Adjustments:
Implemented improved security measures, particularly focusing on Cross-Site Scripting (XSS) vulnerabilities.
Conducted a thorough security review and updated vulnerable sections of the code.

Alignment with Keycloak Project:
Updated themes to align more closely with the Keycloak project we previously prepared.
Made the theme compatible with Keycloak versions 22, 23, and 24, ensuring readiness for future updates and removed code from version 19.

Removal of Redundant Code:
Eliminated redundant code that varied between versions and required frequent maintenance.
Streamlined the codebase to reduce the need for reevaluation with each upstream server change.
These improvements will significantly reduce the overhead of maintaining and updating the codebase, ensuring a more stable and secure environment. By aligning with the Keycloak project and addressing deprecated calls and security vulnerabilities, we are setting a solid foundation for future development and updates.

This request corresponds to phase 1 of our 4 phases code conversion plan
Round 2 - to be prepared after r1 review ( in progress)
Round 3 - full alignment across the to repos with regards to front end (mobile and regular theme)
Round 4 - full implementation of a freemarker based theme that can be inherited by multiple projects, while taking advantage of the previous improvements.

**Review by ivan-c — APPROVED** [review]
Looks great, thank you!

(I copied the description from your comment into the PR description)

**Pull request merged**
