### PR TITLE
Feature/keycloak : allow custom email texts

### PR DESCRIPTION
**Pull request by achen2401**
Per Clara's request: change the word "credentials" to "password" in password reset email.  See related google doc thread [here](https://docs.google.com/document/d/1erdM-yUWYbPkoQMIHsOU3-os1ysXqWBRETmFGOWPO0E/edit?disco=AAABEt0AjJE)

Please see attached screenshot

Before Change:
emailBeforeChange

After Change:
EmailAfterChange

### CODE REVIEW

**Comment by achen2401** [comment]
@mcjustin & @ivan-c I have only tried this out in my local keycloak instance. I'd be great if you can try out these changes and see if they worked for you too?

**Review by mcjustin — APPROVED** [review]
Thanks @achen2401 Looks good to me... Not able to test in my deploy ATM

**Review by ivan-c — APPROVED** [review]
Looks good! Did a quick test and didn't find any issues

image

**Comment by ivan-c** [comment]
@mcjustin 

I'd like to be cautious about over-customizing keycloak. It makes sense to tailor the language to the needs of a project, but any changes to the default keycloak text require us understand, maintain and remember these customizations between keycloak releases, and make things like i18n an extra engineering effort

**Pull request merged**
